### ISSUE TITLE
JSON Generator

### ISSUE THREAD

**Issue by KishonShrill** [syncopika/basic-JSON-generator#1]
Lacking CSS, UI, and mobile responsiveness. 

I would like to contribute a little on its UI and .css since this project has helped me greatly.

**Comment by syncopika** [comment]
hey @KishonShrill,

Thanks so much for your interest and I'm very glad to know it's been helpful to you! :)

Yes, please feel free to make PRs - I'd be happy to review and accept them.

Thank you!
